from app.prompts.system_prompts import (
    ORCHESTRATOR_SYSTEM_PROMPT,
    PROMPT_ENGINEER_SYSTEM_PROMPT,
    VIDEO_EDITOR_SYSTEM_PROMPT,
    QA_REVIEWER_SYSTEM_PROMPT,
    GENERIC_PROMPT_GENERATION_SYSTEM_PROMPT,
    VIDEO_REPLICATION_SYSTEM_PROMPT,
    VIDEO_ANALYSIS_SYSTEM_PROMPT,
    REACT_AGENT_SYSTEM_PROMPT,
    SWARM_LEAD_SYSTEM_PROMPT,
)

__all__ = [
    "ORCHESTRATOR_SYSTEM_PROMPT",
    "PROMPT_ENGINEER_SYSTEM_PROMPT",
    "VIDEO_EDITOR_SYSTEM_PROMPT",
    "QA_REVIEWER_SYSTEM_PROMPT",
    "GENERIC_PROMPT_GENERATION_SYSTEM_PROMPT",
    "VIDEO_REPLICATION_SYSTEM_PROMPT",
    "VIDEO_ANALYSIS_SYSTEM_PROMPT",
    "REACT_AGENT_SYSTEM_PROMPT",
    "SWARM_LEAD_SYSTEM_PROMPT",
]
